sudo: false
language: java
script:
  - jdk_switcher use openjdk11
  - # do stuff with OpenJDK 11
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME
  - # do stuff with open OpenJDK 11
jdk:
        - openjdk11
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
